const translations: Record<string, Record<string, string>> = {
  en: {
    unlock_premium: "Unlock Premium Scripts",
    complete_1_task: "Complete 2 easy tasks to get your premium scripts for free",
    complete_task: "Complete the task to get",
    checking_completion: "Complete the task",
    task_in_progress: "Task in progress",
    loading_offers: "Loading offers...",
    failed_to_load: "Failed to load offers",
    try_again: "Try again",
    reward: "Reward:",
    start_task: "Start task",
    no_offers: "No offers available",
    refresh: "Refresh",
    very_easy: "VERY EASY",
    easy: "EASY",
    medium: "MEDIUM",
  },
  es: {
    unlock_premium: "Desbloquea Scripts Premium",
    complete_1_task: "Completa 2 tareas fáciles para obtener tus scripts premium gratis",
    complete_task: "Completa la tarea para obtener",
    checking_completion: "Completa la tarea",
    task_in_progress: "Tarea en progreso",
    loading_offers: "Cargando ofertas...",
    failed_to_load: "Error al cargar ofertas",
    try_again: "Intentar de nuevo",
    reward: "Recompensa:",
    start_task: "Comenzar tarea",
    no_offers: "No hay ofertas disponibles",
    refresh: "Actualizar",
    very_easy: "MUY FÁCIL",
    easy: "FÁCIL",
    medium: "MEDIO",
  },
  fr: {
    unlock_premium: "Déverrouiller les scripts premium",
    complete_1_task: "Complétez 2 tâches faciles pour obtenir vos scripts premium gratuitement",
    complete_task: "Complétez la tâche pour obtenir",
    checking_completion: "Complétez la tâche",
    task_in_progress: "Tâche en cours",
    loading_offers: "Chargement des offres...",
    failed_to_load: "Erreur lors du chargement des offres",
    try_again: "Réessayer",
    reward: "Récompense:",
    start_task: "Commencer la tâche",
    no_offers: "Aucune offre disponible",
    refresh: "Actualiser",
    very_easy: "TRÈS FACILE",
    easy: "FACILE",
    medium: "MOYEN",
  },
  de: {
    unlock_premium: "Premium-Skripte freischalten",
    complete_1_task: "Schließen Sie 2 einfache Aufgaben ab, um Ihre Premium-Skripte kostenlos zu erhalten",
    complete_task: "Schließen Sie die Aufgabe ab, um zu erhalten",
    checking_completion: "Schließen Sie die Aufgabe ab",
    task_in_progress: "Aufgabe läuft",
    loading_offers: "Angebote werden geladen...",
    failed_to_load: "Fehler beim Laden von Angeboten",
    try_again: "Erneut versuchen",
    reward: "Belohnung:",
    start_task: "Aufgabe starten",
    no_offers: "Keine Angebote verfügbar",
    refresh: "Aktualisieren",
    very_easy: "SEHR EINFACH",
    easy: "EINFACH",
    medium: "MITTEL",
  },
  pt: {
    unlock_premium: "Desbloquear Scripts Premium",
    complete_1_task: "Complete 2 tarefas fáceis para obter seus scripts premium gratuitamente",
    complete_task: "Complete a tarefa para obter",
    checking_completion: "Complete a tarefa",
    task_in_progress: "Tarefa em progresso",
    loading_offers: "Carregando ofertas...",
    failed_to_load: "Erro ao carregar ofertas",
    try_again: "Tentar novamente",
    reward: "Recompensa:",
    start_task: "Iniciar tarefa",
    no_offers: "Nenhuma oferta disponível",
    refresh: "Atualizar",
    very_easy: "MUITO FÁCIL",
    easy: "FÁCIL",
    medium: "MÉDIO",
  },
  it: {
    unlock_premium: "Sblocca Script Premium",
    complete_1_task: "Completa 2 attività facili per ottenere i tuoi script premium gratuitamente",
    complete_task: "Completa l'attività per ottenere",
    checking_completion: "Completa l'attività",
    task_in_progress: "Attività in corso",
    loading_offers: "Caricamento offerte...",
    failed_to_load: "Errore nel caricamento delle offerte",
    try_again: "Riprova",
    reward: "Ricompensa:",
    start_task: "Inizia attività",
    no_offers: "Nessuna offerta disponibile",
    refresh: "Aggiorna",
    very_easy: "MOLTO FACILE",
    easy: "FACILE",
    medium: "MEDIO",
  },
  ru: {
    unlock_premium: "Разблокировать премиум-скрипты",
    complete_1_task: "Выполните 2 простых задачи, чтобы получить свои премиум-скрипты бесплатно",
    complete_task: "Выполните задачу, чтобы получить",
    checking_completion: "Выполните задачу",
    task_in_progress: "Задача выполняется",
    loading_offers: "Загрузка предложений...",
    failed_to_load: "Ошибка при загрузке предложений",
    try_again: "Попробовать снова",
    reward: "Награда:",
    start_task: "Начать задачу",
    no_offers: "Нет доступных предложений",
    refresh: "Обновить",
    very_easy: "ОЧЕНЬ ЛЕГКО",
    easy: "ЛЕГКО",
    medium: "СРЕДНЕ",
  },
  ja: {
    unlock_premium: "プレミアムスクリプトをアンロック",
    complete_1_task: "2つの簡単なタスクを完了して、プレミアムスクリプトを無料で取得",
    complete_task: "タスクを完了して取得",
    checking_completion: "タスクを完了してください",
    task_in_progress: "タスク進行中",
    loading_offers: "オファーを読み込み中...",
    failed_to_load: "オファーの読み込みに失敗しました",
    try_again: "もう一度試す",
    reward: "報酬:",
    start_task: "タスクを開始",
    no_offers: "利用可能なオファーはありません",
    refresh: "更新",
    very_easy: "非常に簡単",
    easy: "簡単",
    medium: "中程度",
  },
  zh: {
    unlock_premium: "解锁高级脚本",
    complete_1_task: "完成2个简单任务，免费获取您的高级脚本",
    complete_task: "完成任务以获取",
    checking_completion: "完成任务",
    task_in_progress: "任务进行中",
    loading_offers: "加载优惠...",
    failed_to_load: "加载优惠失败",
    try_again: "重试",
    reward: "奖励:",
    start_task: "开始任务",
    no_offers: "没有可用的优惠",
    refresh: "刷新",
    very_easy: "非常简单",
    easy: "简单",
    medium: "中等",
  },
  ar: {
    unlock_premium: "فتح البرامج النصية المميزة",
    complete_1_task: "أكمل مهمتين سهلتين للحصول على برامجك النصية المميزة مجانًا",
    complete_task: "أكمل المهمة للحصول على",
    checking_completion: "أكمل المهمة",
    task_in_progress: "المهمة قيد التقدم",
    loading_offers: "جاري تحميل العروض...",
    failed_to_load: "فشل تحميل العروض",
    try_again: "حاول مرة أخرى",
    reward: "المكافأة:",
    start_task: "ابدأ المهمة",
    no_offers: "لا توجد عروض متاحة",
    refresh: "تحديث",
    very_easy: "سهل جداً",
    easy: "سهل",
    medium: "متوسط",
  },
  ko: {
    unlock_premium: "프리미엄 스크립트 잠금 해제",
    complete_1_task: "2개의 쉬운 작업을 완료하여 프리미엄 스크립트를 무료로 획득",
    complete_task: "작업을 완료하여 획득",
    checking_completion: "작업을 완료하세요",
    task_in_progress: "작업 진행 중",
    loading_offers: "오퍼 로드 중...",
    failed_to_load: "오퍼 로드 실패",
    try_again: "다시 시도",
    reward: "보상:",
    start_task: "작업 시작",
    no_offers: "사용 가능한 오퍼 없음",
    refresh: "새로고침",
    very_easy: "매우 쉬움",
    easy: "쉬움",
    medium: "중간",
  },
  th: {
    unlock_premium: "ปลดล็อกสคริปต์พรีเมียม",
    complete_1_task: "ทำงาน 2 งานที่ง่ายให้เสร็จเพื่อรับสคริปต์พรีเมียมของคุณฟรี",
    complete_task: "ทำงานให้เสร็จเพื่อรับ",
    checking_completion: "ทำงานให้เสร็จ",
    task_in_progress: "งานกำลังดำเนินการ",
    loading_offers: "กำลังโหลดข้อเสนอ...",
    failed_to_load: "ไม่สามารถโหลดข้อเสนอ",
    try_again: "ลองอีกครั้ง",
    reward: "รางวัล:",
    start_task: "เริ่มงาน",
    no_offers: "ไม่มีข้อเสนอที่พร้อมใช้งาน",
    refresh: "รีเฟรช",
    very_easy: "ง่ายมาก",
    easy: "ง่าย",
    medium: "ปานกลาง",
  },
  vi: {
    unlock_premium: "Mở khóa Tập lệnh Premium",
    complete_1_task: "Hoàn thành 2 nhiệm vụ dễ dàng để nhận các tập lệnh premium của bạn miễn phí",
    complete_task: "Hoàn thành nhiệm vụ để nhận",
    checking_completion: "Hoàn thành nhiệm vụ",
    task_in_progress: "Nhiệm vụ đang tiến hành",
    loading_offers: "Đang tải các ưu đãi...",
    failed_to_load: "Không thể tải các ưu đãi",
    try_again: "Thử lại",
    reward: "Phần thưởng:",
    start_task: "Bắt đầu nhiệm vụ",
    no_offers: "Không có ưu đãi nào",
    refresh: "Làm mới",
    very_easy: "RẤT DỄ",
    easy: "DỄ",
    medium: "TRUNG BÌNH",
  },
  id: {
    unlock_premium: "Buka Kunci Skrip Premium",
    complete_1_task: "Selesaikan 2 tugas mudah untuk mendapatkan skrip premium Anda secara gratis",
    complete_task: "Selesaikan tugas untuk mendapatkan",
    checking_completion: "Selesaikan tugas",
    task_in_progress: "Tugas sedang berlangsung",
    loading_offers: "Memuat penawaran...",
    failed_to_load: "Gagal memuat penawaran",
    try_again: "Coba lagi",
    reward: "Hadiah:",
    start_task: "Mulai tugas",
    no_offers: "Tidak ada penawaran tersedia",
    refresh: "Segarkan",
    very_easy: "SANGAT MUDAH",
    easy: "MUDAH",
    medium: "SEDANG",
  },
  pl: {
    unlock_premium: "Odblokuj Skrypty Premium",
    complete_1_task: "Ukończ 2 proste zadania, aby uzyskać skrypty premium za darmo",
    complete_task: "Ukończ zadanie, aby uzyskać",
    checking_completion: "Ukończ zadanie",
    task_in_progress: "Zadanie w toku",
    loading_offers: "Ładowanie ofert...",
    failed_to_load: "Nie udało się załadować ofert",
    try_again: "Spróbuj ponownie",
    reward: "Nagroda:",
    start_task: "Rozpocznij zadanie",
    no_offers: "Brak dostępnych ofert",
    refresh: "Odśwież",
    very_easy: "BARDZO ŁATWE",
    easy: "ŁATWE",
    medium: "ŚREDNIE",
  },
  tr: {
    unlock_premium: "Premium Komut Dosyalarının Kilidini Aç",
    complete_1_task: "Premium komut dosyalarınızı ücretsiz olarak almak için 2 kolay görevi tamamlayın",
    complete_task: "Almak için görevi tamamlayın",
    checking_completion: "Görevi tamamlayın",
    task_in_progress: "Görev devam ediyor",
    loading_offers: "Teklifler yükleniyor...",
    failed_to_load: "Teklifler yüklenemedi",
    try_again: "Tekrar deneyin",
    reward: "Ödül:",
    start_task: "Görevi başlat",
    no_offers: "Kullanılabilir teklif yok",
    refresh: "Yenile",
    very_easy: "ÇOK KOLAY",
    easy: "KOLAY",
    medium: "ORTA",
  },
  nl: {
    unlock_premium: "Premium Scripts ontgrendelen",
    complete_1_task: "Voltooi 2 eenvoudige taken om je premium scripts gratis te krijgen",
    complete_task: "Voltooi de taak om te krijgen",
    checking_completion: "Voltooi de taak",
    task_in_progress: "Taak in uitvoering",
    loading_offers: "Aanbiedingen laden...",
    failed_to_load: "Aanbiedingen kunnen niet worden geladen",
    try_again: "Probeer opnieuw",
    reward: "Beloning:",
    start_task: "Taak starten",
    no_offers: "Geen aanbiedingen beschikbaar",
    refresh: "Vernieuwen",
    very_easy: "ZEER GEMAKKELIJK",
    easy: "GEMAKKELIJK",
    medium: "GEMIDDELD",
  },
  sv: {
    unlock_premium: "Lås upp Premium-skript",
    complete_1_task: "Slutför 2 enkla uppgifter för att få dina premium-skript gratis",
    complete_task: "Slutför uppgiften för att få",
    checking_completion: "Slutför uppgiften",
    task_in_progress: "Uppgift pågår",
    loading_offers: "Läser in erbjudanden...",
    failed_to_load: "Det gick inte att läsa in erbjudanden",
    try_again: "Försök igen",
    reward: "Belöning:",
    start_task: "Starta uppgift",
    no_offers: "Inga erbjudanden tillgängliga",
    refresh: "Uppdatera",
    very_easy: "MYCKET LÄTT",
    easy: "LÄTT",
    medium: "MEDEL",
  },
  da: {
    unlock_premium: "Lås Premium-scripts op",
    complete_1_task: "Udfør 2 nemme opgaver for at få dine premium-scripts gratis",
    complete_task: "Fuldfør opgaven for at få",
    checking_completion: "Fuldfør opgaven",
    task_in_progress: "Opgave i gang",
    loading_offers: "Indlæser tilbud...",
    failed_to_load: "Kunne ikke indlæse tilbud",
    try_again: "Prøv igen",
    reward: "Belønning:",
    start_task: "Start opgave",
    no_offers: "Ingen tilbud tilgængelige",
    refresh: "Opdater",
    very_easy: "MEGET NEMT",
    easy: "NEMT",
    medium: "MEDIUM",
  },
  no: {
    unlock_premium: "Lås opp Premium-skript",
    complete_1_task: "Fullfør 2 enkle oppgaver for å få dine premium-skript gratis",
    complete_task: "Fullfør oppgaven for å få",
    checking_completion: "Fullfør oppgaven",
    task_in_progress: "Oppgave pågår",
    loading_offers: "Laster inn tilbud...",
    failed_to_load: "Kunne ikke laste inn tilbud",
    try_again: "Prøv igjen",
    reward: "Belønning:",
    start_task: "Start oppgave",
    no_offers: "Ingen tilbud tilgjengelig",
    refresh: "Oppdater",
    very_easy: "VELDIG LETT",
    easy: "LETT",
    medium: "MEDIUM",
  },
  fi: {
    unlock_premium: "Avaa Premium-skriptit",
    complete_1_task: "Suorita 2 helppoa tehtävää saadaksesi premium-skriptisi ilmaiseksi",
    complete_task: "Suorita tehtävä saadaksesi",
    checking_completion: "Suorita tehtävä",
    task_in_progress: "Tehtävä käynnissä",
    loading_offers: "Ladataan tarjouksia...",
    failed_to_load: "Tarjousten lataaminen epäonnistui",
    try_again: "Yritä uudelleen",
    reward: "Palkinto:",
    start_task: "Aloita tehtävä",
    no_offers: "Ei saatavilla olevia tarjouksia",
    refresh: "Päivitä",
    very_easy: "ERITTÄIN HELPPO",
    easy: "HELPPO",
    medium: "KESKITASO",
  },
  cs: {
    unlock_premium: "Odemknout prémiové skripty",
    complete_1_task: "Dokončete 2 snadné úkoly a získejte své prémiové skripty zdarma",
    complete_task: "Dokončete úkol, abyste získali",
    checking_completion: "Dokončete úkol",
    task_in_progress: "Úkol probíhá",
    loading_offers: "Načítání nabídek...",
    failed_to_load: "Nepodařilo se načíst nabídky",
    try_again: "Zkusit znovu",
    reward: "Odměna:",
    start_task: "Spustit úkol",
    no_offers: "Nejsou k dispozici žádné nabídky",
    refresh: "Obnovit",
    very_easy: "VELMI SNADNÉ",
    easy: "SNADNÉ",
    medium: "STŘEDNÍ",
  },
  hu: {
    unlock_premium: "Premium szkriptek feloldása",
    complete_1_task: "Végezzen el 2 egyszerű feladatot a prémium szkriptek ingyenes szerzéséhez",
    complete_task: "Végezzen el egy feladatot a megszerezéshez",
    checking_completion: "Végezzen el egy feladatot",
    task_in_progress: "Feladat folyamatban",
    loading_offers: "Ajánlatok betöltése...",
    failed_to_load: "Az ajánlatok betöltése sikertelen",
    try_again: "Próbálja újra",
    reward: "Jutalom:",
    start_task: "Feladat indítása",
    no_offers: "Nincsenek elérhető ajánlatok",
    refresh: "Frissítés",
    very_easy: "NAGYON KÖNNYŰ",
    easy: "KÖNNYŰ",
    medium: "KÖZEPES",
  },
  ro: {
    unlock_premium: "Deblochează scripturile Premium",
    complete_1_task: "Completați 2 sarcini ușoare pentru a obține scripturile premium gratuit",
    complete_task: "Completați sarcina pentru a obține",
    checking_completion: "Completați sarcina",
    task_in_progress: "Sarcina în curs",
    loading_offers: "Se încarcă ofertele...",
    failed_to_load: "Nu s-au putut încărca ofertele",
    try_again: "Încercați din nou",
    reward: "Recompensă:",
    start_task: "Începeți sarcina",
    no_offers: "Nicio ofertă disponibilă",
    refresh: "Reîmprospătare",
    very_easy: "FOARTE UȘOR",
    easy: "UȘOR",
    medium: "MEDIU",
  },
  el: {
    unlock_premium: "Ξεκλείδωμα Premium Scripts",
    complete_1_task: "Ολοκληρώστε 2 εύκολες εργασίες για να λάβετε τα premium scripts σας δωρεάν",
    complete_task: "Ολοκληρώστε την εργασία για να λάβετε",
    checking_completion: "Ολοκληρώστε την εργασία",
    task_in_progress: "Εργασία σε εξέλιξη",
    loading_offers: "Φόρτωση προσφορών...",
    failed_to_load: "Αποτυχία φόρτωσης προσφορών",
    try_again: "Δοκιμάστε ξανά",
    reward: "Ανταμοιβή:",
    start_task: "Έναρξη εργασίας",
    no_offers: "Δεν υπάρχουν διαθέσιμες προσφορές",
    refresh: "Ανανέωση",
    very_easy: "ΠΟΛΎ ΕΎΚΟΛΟ",
    easy: "ΕΎΚΟΛΟ",
    medium: "ΜΕΣΑΊΟ",
  },
  he: {
    unlock_premium: "בטל נעילה של סקריפטים פרימיום",
    complete_1_task: "השלם 2 משימות קלות כדי להשיג את הסקריפטים הפרימיום שלך בחינם",
    complete_task: "השלם את המשימה כדי להשיג",
    checking_completion: "השלם את המשימה",
    task_in_progress: "משימה בעיצומה",
    loading_offers: "טוען הצעות...",
    failed_to_load: "נכשל בטעינת הצעות",
    try_again: "נסה שוב",
    reward: "פרס:",
    start_task: "התחל משימה",
    no_offers: "אין הצעות זמינות",
    refresh: "רענן",
    very_easy: "קל מאוד",
    easy: "קל",
    medium: "בינוני",
  },
  hi: {
    unlock_premium: "प्रीमियम स्क्रिप्ट अनलॉक करें",
    complete_1_task: "अपनी प्रीमियम स्क्रिप्ट मुफ्त में प्राप्त करने के लिए 2 आसान कार्य पूरा करें",
    complete_task: "प्राप्त करने के लिए कार्य पूरा करें",
    checking_completion: "कार्य पूरा करें",
    task_in_progress: "कार्य प्रगति में है",
    loading_offers: "ऑफर लोड हो रहे हैं...",
    failed_to_load: "ऑफर लोड करने में विफल",
    try_again: "फिर से कोशिश करें",
    reward: "पुरस्कार:",
    start_task: "कार्य शुरू करें",
    no_offers: "कोई ऑफर उपलब्ध नहीं",
    refresh: "ताज़ा करें",
    very_easy: "बहुत आसान",
    easy: "आसान",
    medium: "मध्यम",
  },
  uk: {
    unlock_premium: "Розблокувати преміум-скрипти",
    complete_1_task: "Виконайте 2 легких завдання, щоб отримати преміум-скрипти безкоштовно",
    complete_task: "Виконайте завдання, щоб отримати",
    checking_completion: "Виконайте завдання",
    task_in_progress: "Завдання виконується",
    loading_offers: "Завантаження пропозицій...",
    failed_to_load: "Не вдалося завантажити пропозиції",
    try_again: "Спробуйте ще раз",
    reward: "Нагорода:",
    start_task: "Почати завдання",
    no_offers: "Немає доступних пропозицій",
    refresh: "Оновити",
    very_easy: "ДУЖЕ ЛЕГКО",
    easy: "ЛЕГКО",
    medium: "СЕРЕДНЄ",
  },
  sk: {
    unlock_premium: "Odomknúť prémiové skripty",
    complete_1_task: "Dokončite 2 jednoduché úlohy, aby ste získali preferencované skripty zadarmo",
    complete_task: "Dokončite úlohu, aby ste získali",
    checking_completion: "Dokončite úlohu",
    task_in_progress: "Úloha pre
