const translations: Record<string, Record<string, string>> = {
  en: {
    unlock_premium: "Unlock Premium Scripts",
    // <CHANGE> changed from "Complete 1 task to get" to "Complete 2 easy tasks to get your premium scripts for free"
    complete_1_task: "Complete 2 easy tasks to get your premium scripts for free",
    complete_task: "Complete the task to get",
    checking_completion: "Complete the task",
    task_in_progress: "Task in progress",
    loading_offers: "Loading offers...",
    failed_to_load: "Failed to load offers",
    try_again: "Try again",
    reward: "Reward:",
    start_task: "Start task",
    no_offers: "No offers available",
    refresh: "Refresh",
    very_easy: "VERY EASY",
    easy: "EASY",
    medium: "MEDIUM",
  },
  es: {
    unlock_premium: "Desbloquea Scripts Premium",
    // <CHANGE> Spanish translation updated
    complete_1_task: "Completa 2 tareas fáciles para obtener tus scripts premium gratis",
    complete_task: "Completa la tarea para obtener",
    checking_completion: "Completa la tarea",
    task_in_progress: "Tarea en progreso",
    loading_offers: "Cargando ofertas...",
    failed_to_load: "Error al cargar ofertas",
    try_again: "Intentar de nuevo",
    reward: "Recompensa:",
    start_task: "Comenzar tarea",
    no_offers: "No hay ofertas disponibles",
    refresh: "Actualizar",
    very_easy: "MUY FÁCIL",
    easy: "FÁCIL",
    medium: "MEDIO",
  },
  fr: {
    unlock_premium: "Déverrouiller les scripts premium",
    // <CHANGE> French translation updated
    complete_1_task: "Complétez 2 tâches faciles pour obtenir vos scripts premium gratuitement",
    complete_task: "Complétez la tâche pour obtenir",
    checking_completion: "Complétez la tâche",
    task_in_progress: "Tâche en cours",
    loading_offers: "Chargement des offres...",
    failed_to_load: "Erreur lors du chargement des offres",
    try_again: "Réessayer",
    reward: "Récompense:",
    start_task: "Commencer la tâche",
    no_offers: "Aucune offre disponible",
    refresh: "Actualiser",
    very_easy: "TRÈS FACILE",
    easy: "FACILE",
    medium: "MOYEN",
  },
  de: {
    unlock_premium: "Premium-Skripte freischalten",
    // <CHANGE> German translation updated
    complete_1_task: "Schließen Sie 2 einfache Aufgaben ab, um Ihre Premium-Skripte kostenlos zu erhalten",
    complete_task: "Schließen Sie die Aufgabe ab, um zu erhalten",
    checking_completion: "Schließen Sie die Aufgabe ab",
    task_in_progress: "Aufgabe läuft",
    loading_offers: "Angebote werden geladen...",
    failed_to_load: "Fehler beim Laden von Angeboten",
    try_again: "Erneut versuchen",
    reward: "Belohnung:",
    start_task: "Aufgabe starten",
    no_offers: "Keine Angebote verfügbar",
    refresh: "Aktualisieren",
    very_easy: "SEHR EINFACH",
    easy: "EINFACH",
    medium: "MITTEL",
  },
  pt: {
    unlock_premium: "Desbloquear Scripts Premium",
    // <CHANGE> Portuguese translation updated
    complete_1_task: "Complete 2 tarefas fáceis para obter seus scripts premium gratuitamente",
    complete_task: "Complete a tarefa para obter",
    checking_completion: "Complete a tarefa",
    task_in_progress: "Tarefa em progresso",
    loading_offers: "Carregando ofertas...",
    failed_to_load: "Erro ao carregar ofertas",
    try_again: "Tentar novamente",
    reward: "Recompensa:",
    start_task: "Iniciar tarefa",
    no_offers: "Nenhuma oferta disponível",
    refresh: "Atualizar",
    very_easy: "MUITO FÁCIL",
    easy: "FÁCIL",
    medium: "MÉDIO",
  },
  it: {
    unlock_premium: "Sblocca Script Premium",
    // <CHANGE> Italian translation updated
    complete_1_task: "Completa 2 attività facili per ottenere i tuoi script premium gratuitamente",
    complete_task: "Completa l'attività per ottenere",
    checking_completion: "Completa l'attività",
    task_in_progress: "Attività in corso",
    loading_offers: "Caricamento offerte...",
    failed_to_load: "Errore nel caricamento delle offerte",
    try_again: "Riprova",
    reward: "Ricompensa:",
    start_task: "Inizia attività",
    no_offers: "Nessuna offerta disponibile",
    refresh: "Aggiorna",
    very_easy: "MOLTO FACILE",
    easy: "FACILE",
    medium: "MEDIO",
  },
  ru: {
    unlock_premium: "Разблокировать премиум-скрипты",
    // <CHANGE> Russian translation updated
    complete_1_task: "Выполните 2 легких задачи, чтобы получить ваши премиум-скрипты бесплатно",
    complete_task: "Выполните задачу, чтобы получить",
    checking_completion: "Выполните задачу",
    task_in_progress: "Задача выполняется",
    loading_offers: "Загрузка предложений...",
    failed_to_load: "Ошибка при загрузке предложений",
    try_again: "Попробовать снова",
    reward: "Награда:",
    start_task: "Начать задачу",
    no_offers: "Нет доступных предложений",
    refresh: "Обновить",
    very_easy: "ОЧЕНЬ ЛЕГКО",
    easy: "ЛЕГКО",
    medium: "СРЕДНЕ",
  },
  ja: {
    unlock_premium: "プレミアムスクリプトをアンロック",
    // <CHANGE> Japanese translation updated
    complete_1_task: "2つの簡単なタスクを完了して、プレミアムスクリプトを無料で取得",
    complete_task: "タスクを完了して取得",
    checking_completion: "タスクを完了してください",
    task_in_progress: "タスク進行中",
    loading_offers: "オファーを読み込み中...",
    failed_to_load: "オファーの読み込みに失敗しました",
    try_again: "もう一度試す",
    reward: "報酬:",
    start_task: "タスクを開始",
    no_offers: "利用可能なオファーはありません",
    refresh: "更新",
    very_easy: "非常に簡単",
    easy: "簡単",
    medium: "中程度",
  },
  zh: {
    unlock_premium: "解锁高级脚本",
    // <CHANGE> Chinese translation updated
    complete_1_task: "完成2个简单任务，免费获取您的高级脚本",
    complete_task: "完成任务以获取",
    checking_completion: "完成任务",
    task_in_progress: "任务进行中",
    loading_offers: "加载优惠...",
    failed_to_load: "加载优惠失败",
    try_again: "重试",
    reward: "奖励:",
    start_task: "开始任务",
    no_offers: "没有可用的优惠",
    refresh: "刷新",
    very_easy: "非常
